

name: GitHub Profile Summary Cards

on:
  schedule: # Runs every day at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 8
          EXCLUDE: ""
          AUTO_PUSH: true





### 🪪 GitHub Summary Cards

![](https://raw.githubusercontent.com/<SakshiBiradar912>/<SakshiBiradar912>/main/profile-summary-card-output/github/0-profile-details.svg)
![](https://raw.githubusercontent.com/<SakshiBiradar912>/<SakshiBiradar912>/main/profile-summary-card-output/github/1-repos-per-language.svg)
![](https://raw.githubusercontent.com/<SakshiBiradar912>/<SakshiBiradar912>/main/profile-summary-card-output/github/2-most-commit-language.svg)
![](https://raw.githubusercontent.com/<SakshiBiradar912>/<SakshiBiradar912>/main/profile-summary-card-output/github/3-stats.svg)
![](https://raw.githubusercontent.com/<SakshiBiradar912>/<SakshiBiradar912>/main/profile-summary-card-output/github/4-productive-time.svg)
